# Generated by Django 4.2.3 on 2023-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date_patient_dispostion_patient_epic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
