# Generated by Django 4.2.3 on 2023-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dispostion',
        ),
        migrations.AddField(
            model_name='patient',
            name='disposition',
            field=models.CharField(default='', max_length=20),
        ),
    ]
