# Generated by Django 4.2.3 on 2023-07-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_dispostion_patient_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(choices=[('SH', 'Sacred Heart')], default='SH', max_length=50),
        ),
    ]
