# Generated by Django 4.2.3 on 2023-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
